server:
  port: 8085
spring:
  application:
    name: TimeTrackingService
  datasource:
    url:  jdbc:postgresql://localhost:5432/time-tracking-service
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true